### ISSUE TITLE
the make GUI failed

### ISSUE THREAD

**Issue by yd0157** [editeodoro/Bbarolo#16]
Hi , I find that after installation and using the make gui command to create the user-interface, it failed because the include part in util.hh includes something outside. I don't know how to deal with it.

**Comment by editeodoro** [comment]
Hi, compiling the GUI can be tricky because the Makefile is configured for my specific system settings. You will have to change it manually according to your QT installation, compiler and other system settings. 

I can help you out, but I need some more information about the errors you get, I need to know what OS are you on, QT version, libraries etc.

**Comment by yd0157** [comment]
Hi, thanks for replying. I work on ubuntu18.04 and my QT is Qt5.13.2( I'm not sure if the error is because of the qt version).  The errors are that when compiling the utils.hh at the beginning, it can not find the file<Map/voxel.hh>. It's a little amazing for me because the file voxel.hh does exist just in another directory outside Utilities in Map, but even after I change the include to be <../Map/voxel.hh>, it again goes wrong.
Actually I'm not good at programming, so I don't know what's wrong with it. Anyway, the Bbarolo really does me a favor, thanks a lot.

**Comment by editeodoro** [comment]
This particular error can be solved by adding a "-I../" to the INCPATH variable in the src/GUI/Makefile. Then you could run "make" from the src/GUI/Makefile.

Why are you trying to compile the GUI? Do the binaries do not work for you?

Anyway, if you are not familiar with programming, I would recommend you to use the command line rather than compiling the GUI yourself. It will be easier to set up a parameter file and run it from the CL, rather than to figure out all the tricks to compile the GUI on your system.

**Comment by yd0157** [comment]
Hi,  it works and I have created the GUI, thanks a lot. The binaries do not work actually with errors that says cant find libjasper( but I have install it -_-).
And I think I will also learn how to use the CL to use Bbarolo, thanks for advising.
Again thank you for your kindly help, both I and my friends find Bbarolo quite useful.

**Comment by editeodoro** [comment]
Great, I am happy that it was easier than I thought! Let me know if need further help. 
I am closing the issue.
