### ISSUE TITLE
gui problem

### ISSUE THREAD

**Issue by anavudragovic** [editeodoro/Bbarolo#18]
When I run:
make gui
I get an error message:
In file included from bbarolowindow_run.cpp:29:
./../Arrays/header.hh:31:10: fatal error: 'fitsio.h' file not found
#include <fitsio.h> 
         ^~~~~~~~~~
1 error generated.
make[1]: *** [../Build/bbarolowindow_run.o] Error 1
make: *** [gui] Error 2

Thank you for any hint!

**Comment by editeodoro** [comment]
Hi Ana, 
building the GUI from scratch can be very tricky, because there are a number of dependencies that are not properly handled by the configure file and you will need to adjust the Makefiles by hand. Good news is that you do not need the GUI!
I recommend you to use BB from the command line, which will also allow you to exploit the full functionality of the code.
Learning how to write a parameter file will also be less time-wasting and more useful than compiling the GUI.
Setting a parameter file with the examples and the documentation should be quite straightforwards, but I am happy to help if you have any problem/doubt. Just send me an email and I will help you out with your data. 

Enrico

**Comment by anavudragovic** [comment]
Hi,

thank you. I’ve also realized I don’t need gui at all!

The example from the example dir works like charm! Many nice plots produced! 

Thanks, Ana
--------------------------------------------- 
Ana Vudragović
Research Associate
Astronomical Observatory
Volgina 7, 11060 Belgrade, Serbia
