### ISSUE TITLE
Decompose rotation curves into baryons and dark matter?

### ISSUE THREAD

**Issue by MyGithubNotYours** [editeodoro/Bbarolo#22]
Thanks for providing this software. Is it able to decompose the rotation curves into baryons vs dark matter from FITS files? If not, can you suggest software that does decompose from FITS files?

Thanks!

**Comment by editeodoro** [comment]
Hello, BBarolo does not currently do that. Once you have a rotation curve, you can relatively easily write a python script to decompose it into the contribution of baryons and dark matter (with the usual degeneracy on the M/L). You are going to need additional data of course, for example the stellar profile. ROTMAS task in [GIPSY](https://www.astro.rug.nl/~gipsy/) can do that for a number of density profiles, although I would not recommend it if you have never used GIPSY before. Writing your own script is probably the best way to go.

**Comment by MyGithubNotYours** [comment]
@editeodoro thanks much for the feedback. Also, I noticed that @kyleaoman is a contributor here. This past weekend on the physics Stack Exchange forums, he answered the same question (so thanks to you too Mr Oman!). May I ask you one more question here or should I start a new issue?

In BBarolo, I successfully ran it using the example file ngc2403.fits (that comes with BBarolo). However, when I try using other FITS files from the same galaxy (from observatory websites), I get the error:

```
Starting research for possible sources in the cube... 
Searching in progress... Found 7718 items.
  Updating detection map... Done.
  Intermediate list has 7718 objects.
  Merging and Rejecting...  Done.                      
  ... All done.

Final object count = 0


Estimating initial parameters...  3DFIT ERROR: No sources detected in the datacube. Cannot fit!!! 
terminate called without an active exception
Aborted (core dumped)

```

I've tried setting all parameters to -1 and toggling the non-numerical parameters, but I can't get past this error. What am I doing wrong? I am fully aware that I am most likely the problem. I'm brand new at this subject.

Here's an example of FITS files for the same galaxy (ngc2403) as the one you provide with BBarolo:
https://irsa.ipac.caltech.edu/data/SPITZER/LVL/galaxies/NGC2403.html

Let me know if I should start a new issue for this new question.

**Comment by editeodoro** [comment]
Hello, 
BBarolo is made to work with 3D emission-line data (e.g. HI, CO, Ha observations, etc), it will not work with any other type of astronomical data. The FITS files that you're trying are to use are, for example, IR data from Spitzer. These data do not have enough information to derive a rotation curve, because they lack a spectral axis. Depending on your science goals, there are a number of data archives where you can find 3D emission line data (for example [HALOGAS](https://www.astron.nl/halogas/data.php), [THINGS](https://www2.mpia-hd.mpg.de/THINGS/Data.html) surveys). But again, that depends on what you're trying to do...

If you just want rotation curve decompositions for a bunch of galaxies, people have already done that for basically any galaxy that has been observed so far. I recommend you to take a look to the [SPARC](http://astroweb.cwru.edu/SPARC/) sample for example.
