### ISSUE TITLE
Issue with kinematic fitting failing

### ISSUE THREAD

**Issue by siangphillips** [editeodoro/Bbarolo#33]
Hi,

I'm trying to use 3DBbarolo to fit simulated high-redshift galaxy data cubes. I have been able to successfully do this with one datacube, but with another the fitting errors out with this message: 

   Preparing a bunch of cool outputs...
    Extracting guileless 2D maps... Done.
    Deriving sublime radial profile... Done.
    Calculating the very last model...corrupted size vs. prev_size
Aborted (core dumped)

I have tried to investigate this error but I don't recognise it and couldn't find any useful information on how to deal with it. Do you have any idea what could have caused this error? I was running 3DBbarolo with a .par file, where the .par file has this structure: 

FITSFILE   Opuntia_bbarolo.fits 
OUTFOLDER Opuntia
3DFIT       true
NRADII  2
RADSEP    0.16
VSYS	161.673 
XPOS     6.5
YPOS     6.5
INC    60.0
Z0          0.001
FREE      VROT VDISP 
TWOSTAGE True
NORM AZIM
MASK SEARCH
SNRCUT	   3
GROWTHCUT   2.8
NORMALCUBE True

Many thanks, Sian

**Comment by editeodoro** [comment]
Hello Sian, thanks for using BB for your research!

That is an error that I've never seen before, so I'll need to investigate it further. It may be due to some parameter in the fits header that the code is not understanding. 

Can you please send me by email the datacube and the parameter file that gives the error?

Thanks, 
Enrico
