### ISSUE TITLE
A stange result

### ISSUE THREAD

**Issue by Couleyr** [editeodoro/Bbarolo#40]
Dear Prof.,
Sorry to bother you again！
When we used the Bbarolo to model the Halpha emission of a galaxy, we obtained a velocity field distribution (moment1) inconsistent with its spectral velocity range.
May I ask why this is happening?
The attachment contains all the files we have used.

Cheers,
Peibin Chen
2024/11/11
[Files.zip](https://github.com/user-attachments/files/17698803/Files.zip)

**Comment by editeodoro** [comment]
Hi Peibin, I think the problem is in the "definition" of velocity. For optical data, BBarolo uses by default the velocity from relativistic Doppler effect, and you're comparing it to the classic "optical" velocity. You can force BB to use the optical definition by setting VELDEF=OPTICAL.

Cheers, 
Enrico

**Comment by Couleyr** [comment]
Thank you for your reply, it was very helpful.
In fact, we have done the same for other optical emission lines (e.g., OIII5007) of this galaxy, but only Halpha has such a problem.
